BATCH_SIZE = 100
IMAGE_SIZE = 32
CHANNELS = 3

EPOCHS = 10
LEARNING_RATE = 1e-3

NUM_CLASSES = 100

PATCH_SIZE = 4

NUM_PATCHS = (IMAGE_SIZE // PATCH_SIZE) ** 2 

NUM_POSITION_EMBEDDINGS = 2 * (IMAGE_SIZE // PATCH_SIZE)

EMBEDDING_DIM = 256

NUM_LAYERS = 4
NUM_HEADS = EMBEDDING_DIM // NUM_LAYERS

